name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Unit and integration tests
        run: npm run test:ci

      - name: Build production bundle
        run: npm run build

      - name: Capture deployment metadata
        id: metadata
        run: |
          timestamp=$(date --utc +"%Y-%m-%dT%H:%M:%SZ")
          cat <<EOF > deployment-metadata.json
          {
            "pipeline": "azure-static-web-apps",
            "runId": "${{ github.run_id }}",
            "runNumber": "${{ github.run_number }}",
            "repository": "${{ github.repository }}",
            "commit": "${{ github.sha }}",
            "ref": "${{ github.ref }}",
            "actor": "${{ github.actor }}",
            "timestamp": "${timestamp}",
            "eventName": "${{ github.event_name }}"
          }
          EOF

      - name: Upload deployment metadata artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-metadata
          path: deployment-metadata.json

      - name: Upload static bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: mindflow-dist
          path: dist

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/'
          api_location: ''
          output_location: 'dist'

      - name: Summarise deployment
        if: success()
        run: |
          echo "### ✅ Azure Static Web Apps deployment" >> "$GITHUB_STEP_SUMMARY"
          echo "- Commit: ${{ github.sha }}" >> "$GITHUB_STEP_SUMMARY"
          echo "- Run: [#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> "$GITHUB_STEP_SUMMARY"
          echo "- Actor: ${{ github.actor }}" >> "$GITHUB_STEP_SUMMARY"

      - name: Flag deployment failure
        if: failure()
        run: |
          echo "### ❌ Azure Static Web Apps deployment failed" >> "$GITHUB_STEP_SUMMARY"
          echo "Review uploaded artifacts for deployment metadata and build output." >> "$GITHUB_STEP_SUMMARY"
